SUPPORTED_EXTENSIONS = (".xlsx", ".xls")

DEBUG_EXPORT_EXTRACT = True
DEBUG_EXPORT_RAW = False
DEBUG_EXPORT_STAGING = True
DEBUG_EXPORT_DIM_SALE_TYPE = True
DEBUG_EXPORT_DIM_SPOT = True
DEBUG_EXPORT_DIM_DATE = True
DEBUG_EXPORT_DIM_MOVEMENT_TYPE = True
DEBUG_EXPORT_PRODUCT_IDENTITY = True
DEBUG_EXPORT_DIM_PRODUCT = True
DEBUG_EXPORT_FACT_SALES_QUANTITY = True
DEBUG_EXPORT_FACT_SALES_GROSS = True
DEBUG_EXPORT_FACT_PRODUCTCOST = True
DEBUG_EXPORT_PRODUCTCOST_DAILY_LOOKUP = True
DEBUG_EXPORT_FACT_INVENTORY_MOVEMENT = True

EXTRACT_EXPORT_FILENAME = "01_extract_combined.xlsx"
RAW_EXPORT_FILENAME = "raw_extract.csv"
RAW_DEBUG_EXPORT_FILENAME = "02_raw_debug.xlsx"
STAGING_DEBUG_EXPORT_FILENAME = "03_staging_debug.xlsx"

DIM_SALE_TYPE_DEBUG_EXPORT_FILENAME = "10_dim_sale_type.xlsx"
DIM_SPOT_DEBUG_EXPORT_FILENAME = "11_dim_spot.xlsx"
DIM_DATE_DEBUG_EXPORT_FILENAME = "12_dim_date.xlsx"
DIM_MOVEMENT_TYPE_DEBUG_EXPORT_FILENAME = "13_dim_movement_type.xlsx"

PRODUCT_IDENTITY_DEBUG_EXPORT_FILENAME = "20_product_identity.xlsx"
DIM_PRODUCT_DEBUG_EXPORT_FILENAME = "21_dim_product.xlsx"

FACT_SALES_QUANTITY_DEBUG_EXPORT_FILENAME = "30_fact_sales_quantity.xlsx"
FACT_SALES_GROSS_DEBUG_EXPORT_FILENAME = "31_fact_sales_gross.xlsx"
FACT_PRODUCTCOST_DEBUG_EXPORT_FILENAME = "32_fact_productcost.xlsx"
PRODUCTCOST_DAILY_LOOKUP_DEBUG_EXPORT_FILENAME = "33_productcost_daily_lookup.xlsx"
FACT_INVENTORY_MOVEMENT_DEBUG_EXPORT_FILENAME = "34_fact_inventory_movement.xlsx"

DIM_DATE_EXPORT_FILENAME = "dim_date.csv"
DIM_SPOT_EXPORT_FILENAME = "dim_spot.csv"
DIM_SALE_TYPE_EXPORT_FILENAME = "dim_sale_type.csv"
DIM_MOVEMENT_TYPE_EXPORT_FILENAME = "dim_movement_type.csv"
DIM_PRODUCT_EXPORT_FILENAME = "dim_product.csv"

FACT_SALES_QUANTITY_EXPORT_FILENAME = "fact_sales_quantity.csv"
FACT_SALES_GROSS_EXPORT_FILENAME = "fact_sales_gross.csv"
FACT_PRODUCTCOST_EXPORT_FILENAME = "fact_productcost.csv"
FACT_INVENTORY_MOVEMENT_EXPORT_FILENAME = "fact_inventory_movement.csv"